eval:
  model_dir: "../../model"
  data_path: "../../data/car_t_ires.fasta"
  max_length: 1024
  hidden_size: 768
  inter_size: 3072
  num_heads: 12
  num_layers: 12
  bs_train: 32
  bs_test: 32
  log_steps: 320
  save_steps: 320
  num_epoches: 10
embed:
  model_dir: "../../model"
  data_path: "../../data/car_t_ires.fasta"
  output_path: "../../output/car-t_ires.npy"
  max_length: 1024